name: 'Release'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' 
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Read Bridge ${{ github.ref_name }}'
          releaseBody: |
            # 📚 Read Bridge ${{ github.ref_name }}

            ## 🚀 快速下载 / Quick Download

            **Windows**
            [![Download EXE](https://img.shields.io/badge/Download_EXE-Windows-blue?style=for-the-badge)](https://github.com/WindChimeEcho/read-bridge/releases/download/${{ github.ref_name }}/read-bridge_${{ github.ref_name }}_x64-setup.exe)
            [![Download MSI](https://img.shields.io/badge/Download_MSI-Windows-lightblue?style=for-the-badge)](https://github.com/WindChimeEcho/read-bridge/releases/download/${{ github.ref_name }}/read-bridge_${{ github.ref_name }}_x64_zh-CN.msi)

            **macOS**
            [![Download DMG Intel](https://img.shields.io/badge/Download_DMG-Intel_Mac-silver?style=for-the-badge)](https://github.com/WindChimeEcho/read-bridge/releases/download/${{ github.ref_name }}/read-bridge_${{ github.ref_name }}_x64.dmg)
            [![Download DMG Silicon](https://img.shields.io/badge/Download_DMG-Apple_Silicon-silver?style=for-the-badge)](https://github.com/WindChimeEcho/read-bridge/releases/download/${{ github.ref_name }}/read-bridge_${{ github.ref_name }}_aarch64.dmg)

            **Linux**
            [![Download AppImage](https://img.shields.io/badge/Download_AppImage-Linux-orange?style=for-the-badge)](https://github.com/WindChimeEcho/read-bridge/releases/download/${{ github.ref_name }}/read-bridge_${{ github.ref_name }}_amd64.AppImage)
            [![Download DEB](https://img.shields.io/badge/Download_DEB-Ubuntu/Debian-red?style=for-the-badge)](https://github.com/WindChimeEcho/read-bridge/releases/download/${{ github.ref_name }}/read-bridge_${{ github.ref_name }}_amd64.deb)

            ---
            **Read Bridge** - Your AI Reading Companion for Language Mastery | 您的AI语言学习阅读伙伴
            
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
